apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    targetRevision: 7.8.2
    chart: argo-cd
    helm:
      releaseName: argocd
      values: |  
        dex:
          enabled: false
        notifications:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5


