apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
   - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.14.1
    chart: external-secrets
    helm:
      releaseName: external-secrets
      values: |  
        extraObjects:
          - apiVersion: external-secrets.io/v1alpha1
            kind: ClusterSecretStore
            metadata:
              name: awssm-store
            spec:
              provider:
                aws:
                  service: SecretsManager
                  region: us-east-1
                  auth:
                    secretRef:
                      accessKeyIDSecretRef:
                        name: awssm-secret
                        key: access-key
                        namespace: external-secrets
                      secretAccessKeySecretRef:
                        name: awssm-secret
                        key: secret-access-key
                        namespace: external-secrets
          - apiVersion: external-secrets.io/v1alpha1
            kind: ExternalSecret
            metadata:
              name: backend-dev-secret
              namespace: dev
            spec:
              refreshInterval: 5m0s
              secretStoreRef:
                name: awssm-store
                kind: ClusterSecretStore
              target:
                name: backend-secret
                creationPolicy: Owner
              dataFrom:
                - key: myapp/dev/backend  # Назва секрету
                    
          - apiVersion: external-secrets.io/v1alpha1
            kind: ExternalSecret
            metadata:
              name: backend-prod-secret
              namespace: prod
            spec:
              refreshInterval: 5m0s
              secretStoreRef:
                name: awssm-store
                kind: ClusterSecretStore
              target:
                name: backend-secret
                creationPolicy: Owner
              dataFrom:
                - key: myapp/prod/backend  # Назва секрету
                   
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
