apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application }}-service
  labels:
    app: {{ .Values.application }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
      protocol: TCP
  selector:
       app: {{ printf "%s-%s" .Release.Name .Values.application }}
