name: Build and Push Frontend Docker Image

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select the target environment"
        required: true
        type: choice
        options:
          - dev
          - prod

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR Public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: public

      - name: Get Short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)" >> $GITHUB_ENV

      - name: Set Backend URL
        run: |
          if [ "${{ inputs.environment }}" == "dev" ]; then
            echo "BACKEND_URL=https://dev.myapp.local" >> $GITHUB_ENV
          else
            echo "BACKEND_URL=https://myapp.local" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Image
        env:
          AWS_ECR_REGISTRY: ${{ secrets.FRONTEND_ECR_REGISTRY }}
          AWS_ECR_REGISTRY_ALIAS: ${{ secrets.FRONTEND_ECR_REGISTRY_ALIAS }}
          AWS_ECR_REPOSITORY: frontend
          FRONTEND_REPOSITORY: https://github.com/fastapi/full-stack-fastapi-template.git#0.7.1:frontend
          IMAGE_TAG: ${{ env.SHORT_SHA }}
        run: |
          docker build --build-arg VITE_API_URL=$BACKEND_URL -t $AWS_ECR_REGISTRY/$AWS_ECR_REGISTRY_ALIAS/$AWS_ECR_REPOSITORY:$IMAGE_TAG $FRONTEND_REPOSITORY
          docker push $AWS_ECR_REGISTRY/$AWS_ECR_REGISTRY_ALIAS/$AWS_ECR_REPOSITORY:$IMAGE_TAG

          if [ "${{ inputs.environment }}" == "prod" ]; then
            docker tag $AWS_ECR_REGISTRY/$AWS_ECR_REGISTRY_ALIAS/$AWS_ECR_REPOSITORY:$IMAGE_TAG $AWS_ECR_REGISTRY/$AWS_ECR_REGISTRY_ALIAS/$AWS_ECR_REPOSITORY:latest
            docker push $AWS_ECR_REGISTRY/$AWS_ECR_REGISTRY_ALIAS/$AWS_ECR_REPOSITORY:latest
          fi

      - name: Update Image Tag in Values
        run: |
          sed -i "s/tag: .*/tag: ${{ env.SHORT_SHA }}/" custom-charts/frontend/values-${{ github.event.inputs.environment }}.yaml
          echo "Updated image tag to ${{ env.SHORT_SHA }} in values-${{ github.event.inputs.environment }}.yaml"
